#!/bin/sh

sysprofile=/etc/xprofile
[ -f "$sysprofile" ] && . "$sysprofile"

userprofile="$XDG_CONFIG_HOME/X11/xprofile"
[ -f "$userprofile" ] && . "$userprofile"

sysresources=/etc/X11/xinit/.Xresources
if [ -f "$sysresources" ]; then
	xrdb -merge $sysresources
fi

sysmodmap=/etc/X11/xinit/.Xmodmap
if [ -f "$sysmodmap" ]; then
	xmodmap $sysmodmap
fi

userresources="$XDG_CONFIG_HOME/X11/xresources"
if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

usermodmap="$XDG_CONFIG_HOME/X11/xmodmap"
if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

session=$1 && shift 1
xmonadbin="$XDG_CACHE_HOME/xmonad/xmonad-x86_64-linux"

case "$session" in
xmonad) exec "$xmonadbin" "$@" ;;
*) exec "$session" "$@" ;;
esac
