#!/bin/sh

export XCURSOR_SIZE=29

env XSECURELOCK_PASSWORD_PROMPT=time xss-lock xsecurelock &
xsetroot -cursor_name left_ptr &
xkbcomp $HOME/.config/X11/xkbrc $DISPLAY &>/dev/null &
layout-auto &
dunst -conf $HOME/.config/dunst/dunstrc &
copyq &
aw-server-rust | aw-watcher-afk | aw-watcher-window &
# xset r rate 250 45 -display $DISPLAY &

if test -d "/sys/class/power_supply/BAT"*; then
	cbatticon &
fi
